# Generated by Django 4.1.2 on 2022-10-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_readingupdate_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='last_page',
            new_name='end_location',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='first_page',
            new_name='start_location',
        ),
    ]
