# Generated by Django 4.1.2 on 2022-10-21 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_last_page_book_end_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
