# Generated by Django 4.1.2 on 2022-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
