# Generated by Django 4.1.2 on 2022-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingupdate',
            options={'ordering': ['date', 'book']},
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kindle Locations'), (1, 'Pages')], default=1),
        ),
    ]
