# Generated by Django 4.1.2 on 2023-03-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_readingupdate_options_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingupdate',
            name='progress',
        ),
        migrations.AddField(
            model_name='readingupdate',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
