# Generated by Django 4.2 on 2024-02-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_readingupdate_progress_readingupdate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
