#!/usr/bin/env bash

set -e

interactive=true
fromprod=false
while [ $# -gt 0 ]; do
  	case "$1" in
    	--no-input)
    	  	interactive=false
      	;;
  	esac
	case "$1" in
	    --from-prod)
		    fromprod=true
		;;
	esac
	shift


done

if $interactive ; then
    echo "WARNING!! This script REMOVE your LOCAL peregrin database and you LOSE all the data."
    read -p "Are you sure you want to delete all data? (y/N): " -n 1 -r
    echo    # (optional) move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]] ; then
        exit 1
    fi
fi

if [ -f ./peregrin/db.sqlite3 ]; then
    rm ./peregrin/db.sqlite3
else
    echo "==> Removing peregrin_two DB if existing"
    dropdb peregrin_two --if-exists

    echo "==> Re-create peregrin_two DB"
	createdb peregrin_two
fi

cd "$(dirname "$0")/.."

echo "==> Migrating DB"
pipenv run python ./peregrin/manage.py migrate

if $fromprod; then
	echo "==> Pulling from prod..."
	heroku run python -W ignore manage.py dumpdata books history --natural-foreign --natural-primary -a peregrin -- > tmpdump.json
	pipenv run python peregrin/manage.py import_legacy_json tmpdump.json
	rm tmpdump.json
fi;


echo "==> Setting up git hooks"
git config core.hooksPath .git-hooks

echo "==> App is now ready to go!"
