#!/usr/bin/env bash

set -e

interactive=true
fromprod=false
while [ $# -gt 0 ]; do
  	case "$1" in
    	--no-input)
    	  	interactive=false
      	;;
  	esac
	case "$1" in
	    --from-prod)
		    fromprod=true
		;;
	esac
	shift


done

if $interactive ; then
    echo "WARNING!! This script REMOVE your LOCAL heartguide database and you LOSE all the data."
    read -p "Are you sure you want to delete all data? (y/N): " -n 1 -r
    echo    # (optional) move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]] ; then
        exit 1
    fi
fi

if [ -f ./peregrin/db.sqlite3 ]; then
    rm ./peregrin/db.sqlite3
fi

cd "$(dirname "$0")/.."

echo "==> Migrating DB"
pipenv run python ./peregrin/manage.py migrate

if $fromprod; then
	echo "==> Pulling from prod..."
	echo "🚨 Not implemented! 🚨"
fi;


echo "==> Setting up git hooks"
git config core.hooksPath .git-hooks

echo "==> App is now ready to go!"
